### PR TITLE
Build badgen for browsers

### PR DESCRIPTION
**Pull request by bokub**
Use [Lyo](https://github.com/bokub/lyo) to build badgen as a browser-compatible library, so you can use it for something like a badge builder

```html
<script src="https://cdn.jsdelivr.net/npm/badgen@2.4.5/dist/badgen.min.js"></script>

<script>
  var svgString = badgen({
    // ...
  });
</script>
```

### CODE REVIEW

**Comment by amio** [comment]
Nice! Thanks @bokub

**Comment by bokub** [comment]
No problem!
Of course, you need to `npm publish` in order to make the build available.

And maybe you could add the [jsDelivr URL](https://cdn.jsdelivr.net/npm/badgen@latest/dist/badgen.min.js) to your README, otherwise people won't notice that a build is available

**Comment by amio** [comment]
I was going to publish only bundled version to npm, but found the bundling hurt performance badly 🤨

```
## bundled

[classic] style, long params x 185,194 ops/sec ±1.01% (87 runs sampled)
[classic] style, full params x 314,503 ops/sec ±0.64% (96 runs sampled)
[classic] style, with emoji  x 361,927 ops/sec ±0.87% (89 runs sampled)
[classic] style, with icon   x 364,181 ops/sec ±0.37% (95 runs sampled)
   [flat] style, long params x 178,009 ops/sec ±0.30% (95 runs sampled)
   [flat] style, full params x 262,668 ops/sec ±2.21% (92 runs sampled)
   [flat] style, with emoji  x 289,207 ops/sec ±0.43% (92 runs sampled)
   [flat] style, with icon   x 291,603 ops/sec ±0.67% (93 runs sampled)
 
## source

[classic] style, long params x 960,341 ops/sec ±1.66% (92 runs sampled)
[classic] style, full params x 1,346,764 ops/sec ±1.13% (94 runs sampled)
[classic] style, with emoji  x 1,316,054 ops/sec ±1.78% (91 runs sampled)
[classic] style, with icon   x 1,074,485 ops/sec ±0.40% (92 runs sampled)
   [flat] style, long params x 659,249 ops/sec ±0.51% (94 runs sampled)
   [flat] style, full params x 731,565 ops/sec ±0.81% (94 runs sampled)
   [flat] style, with emoji  x 747,136 ops/sec ±0.37% (94 runs sampled)
   [flat] style, with icon   x 632,309 ops/sec ±0.66% (94 runs sampled)
```

**Comment by bokub** [comment]
Oh, you really shouldn't use the bundle in node.js, it would be terrible. You have keep the existing code for node_modules usage, and the bundle for browser usage.

Of course the performance is degraded, because the bundle contains extra code to make it work in most browser
s (includuding old ones).

By the way, how did you import/require the bundle for your benchmark?

**Pull request merged**
