### PR TITLE
Minify SVG output

### PR DESCRIPTION
**Pull request by amio**
Result:
```
<svg xmlns="http://www.w3.org/2000/svg" width="75.4" height="20"><linearGradient id="a" x2="0" y2="100%"><stop offset="0" stop-color="#EEE" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="m"><rect width="75.4" height="20" rx="3" fill="#FFF"/></mask><g mask="url(#m)"><rect width="34.6" height="20" fill="#555"/><rect x="34.6" width="40.8" height="20" fill="#A3E"/><rect width="75.4" height="20" fill="url(#a)"/></g><g fill="#fff" text-anchor="start" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11"><text x="7" y="14.8" fill="#000" opacity="0.25">chat</text><text x="6" y="13.8">chat</text><text x="40.1" y="14.8" fill="#000" opacity="0.25">gitter</text><text x="39.1" y="13.8">gitter</text></g></svg>
```

### CODE REVIEW

**Comment by wei** [comment]
Close #1 when merged 😃

**Comment by amio** [comment]
After running benchmarks, seems [this](https://github.com/amio/badgen/compare/master...pr3) did have a significant effect in performance 😢
```
~/g/badgen [pr3] » npm run bench                                                                                13:01:39

> badgen@2.0.0 bench /Users/Amio/git/badgen
> node bench/index.js

[classic] style, long params  x 234,874 ops/sec ±2.34% (88 runs sampled)
[classic] style, full params  x 253,784 ops/sec ±3.64% (85 runs sampled)
   [flat] style, long params  x 237,951 ops/sec ±3.31% (79 runs sampled)
   [flat] style, full params  x 265,422 ops/sec ±3.00% (85 runs sampled)
[classic] style, emoji params x 225,411 ops/sec ±1.23% (86 runs sampled)
 
~/g/badgen [pr3] » git checkout master                                                                          13:07:55
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
 
~/g/badgen [master] » npm run bench                                                                             13:08:00

> badgen@2.0.0 bench /Users/Amio/git/badgen
> node bench/index.js

[classic] style, long params  x 657,776 ops/sec ±1.39% (88 runs sampled)
[classic] style, full params  x 874,906 ops/sec ±1.63% (87 runs sampled)
   [flat] style, long params  x 476,113 ops/sec ±3.53% (85 runs sampled)
   [flat] style, full params  x 505,272 ops/sec ±3.24% (82 runs sampled)
[classic] style, emoji params x 619,655 ops/sec ±3.21% (87 runs sampled)
```

**Comment by wei** [comment]
Year regex search & replace definitely affects performance to some degree. & you probably don't want to use the minified version directly in the code to maintain source code readibility right? 

This is an alternative, clean version with some minor indention adjustments in source code with no performance impact. 
https://github.com/amio/badgen/compare/master...wei:patch-3?expand=1

It does make indentions in the source code look a bit awkward. You don't have to do it if you feel it's unnecessary. 🤓

**Comment by amio** [comment]
Yea, I would like to keep source a better looking, but thank you anyway 🤗

**Pull request closed without merging**
